{
 "title": "SmartPi",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.datasets[*].phases[0].values[2].data",
       "name": "Power 1"
      },
      {
       "jsonPath": "$.datasets[*].phases[1].values[2].data",
       "language": "jsonpath",
       "name": "Power 2"
      },
      {
       "jsonPath": "$.datasets[*].phases[2].values[2].data",
       "language": "jsonpath",
       "name": "Power 3"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[0].data",
       "language": "jsonpath",
       "name": "Current 1"
      },
      {
       "jsonPath": "$.datasets[*].phases[1].values[0].data",
       "language": "jsonpath",
       "name": "Current 2"
      },
      {
       "jsonPath": "$.datasets[*].phases[2].values[0].data",
       "language": "jsonpath",
       "name": "Current 3"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[1].data",
       "language": "jsonpath",
       "name": "Voltage 1"
      },
      {
       "jsonPath": "$.datasets[*].phases[1].values[1].data",
       "language": "jsonpath",
       "name": "Voltage 2"
      },
      {
       "jsonPath": "$.datasets[*].phases[2].values[1].data",
       "language": "jsonpath",
       "name": "Voltage 3"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[4].data",
       "language": "jsonpath",
       "name": "Frequency 1"
      },
      {
       "jsonPath": "$.datasets[*].phases[1].values[4].data",
       "language": "jsonpath",
       "name": "Frequency 2"
      },
      {
       "jsonPath": "$.datasets[*].phases[2].values[4].data",
       "language": "jsonpath",
       "name": "Frequency 3"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[3].data",
       "language": "jsonpath",
       "name": "CosPhi 1"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[3].data",
       "language": "jsonpath",
       "name": "CosPhi 2"
      },
      {
       "jsonPath": "$.datasets[*].phases[0].values[3].data",
       "language": "jsonpath",
       "name": "CosPhi 3"
      }
     ],
     "method": "GET",
     "urlPath": "/api/all/all/now"
    }
   ]
  },
  {
   "title": "Power / Phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Energy consumption month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Energy production month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Energy consumption",
   "type": "barchart",
   "description": "15 Min Peak",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\" or r[\"_field\"] == \"P2\" or r[\"_field\"] == \"P3\")\n  |> map(fn: (r) => ({r with _value:            \n                    if r._value >= 0.2 then r._value   // more than 200mW\n                    else 0.0}))\n  |> elapsed(unit: 1s)\n  |> map(fn: (r) => ({ r with elapsed: float(v: r.elapsed)}))\n  |> map(fn: (r) => ({ r with elapsed: if r.elapsed > 60.0 then 60.0           //TEST previous measurement\n                        else r.elapsed}))\n  |> map(fn: (r) => ({ r with power_Ws: r._value * r.elapsed }))\n  |> map(fn: (r) => ({ r with power_kWh: r.power_Ws / 3600000.0}))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"power_kWh\")\n    |> map(fn: (r) => ({r with power_kWh: r.P1 + r.P2 + r.P3 }))\n    |> aggregateWindow(every: 15m, fn: sum, column: \"power_kWh\")\n  \n\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])"
    }
   ]
  },
  {
   "title": "Energy consumption month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\" or r[\"_field\"] == \"P2\" or r[\"_field\"] == \"P3\")\n  |> map(fn: (r) => ({r with _value:\n                    if r._value >= 0.2 then r._value\n                    else 0.0}))\n  |> elapsed(unit: 1s)\n  |> map(fn: (r) => ({ r with elapsed: float(v: r.elapsed)}))\n  |> map(fn: (r) => ({ r with elapsed: if r.elapsed > 60.0 then 60.0           //TEST\n                        else r.elapsed}))\n  |> map(fn: (r) => ({ r with power_Ws: r._value * r.elapsed }))\n  |> map(fn: (r) => ({ r with power_kWh: r.power_Ws / 3600000.0}))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"power_kWh\")\n  |> map(fn: (r) => ({r with power_kWh: r.P1 + r.P2 + r.P3 }))\n  |> timeShift(duration: -23h) \n  |> aggregateWindow(every: 1d, fn: sum, column: \"power_kWh\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])"
    }
   ]
  },
  {
   "title": "Energy production",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\" or r[\"_field\"] == \"P2\" or r[\"_field\"] == \"P3\")\n  |> map(fn: (r) => ({r with _value:\n                    if r._value < -0.2 then r._value\n                    else 0.0}))\n  |> elapsed(unit: 1s)\n  |> map(fn: (r) => ({ r with elapsed: float(v: r.elapsed)}))\n  |> map(fn: (r) => ({ r with elapsed: if r.elapsed > 60.0 then 60.0           //TEST\n                        else r.elapsed}))\n  |> map(fn: (r) => ({ r with power_Ws: r._value * r.elapsed }))\n  |> map(fn: (r) => ({ r with power_kWh: r.power_Ws / 3600000.0}))\n    |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"power_kWh\")    \n    |> map(fn: (r) => ({r with power_kWh: r.P1 + r.P2 + r.P3 }))\n    |> aggregateWindow(every: 15m, fn: sum, column: \"power_kWh\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])"
    }
   ]
  },
  {
   "title": "Energy production month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\" or r[\"_field\"] == \"P2\" or r[\"_field\"] == \"P3\")\n  |> map(fn: (r) => ({r with _value:\n                    if r._value < -0.2 then r._value\n                    else 0.0}))\n  |> elapsed(unit: 1s)\n  |> map(fn: (r) => ({ r with elapsed: float(v: r.elapsed)}))\n  |> map(fn: (r) => ({ r with elapsed: if r.elapsed > 60.0 then 60.0           //TEST\n                        else r.elapsed}))\n  |> map(fn: (r) => ({ r with power_Ws: r._value * r.elapsed }))\n  |> map(fn: (r) => ({ r with power_kWh: r.power_Ws / 3600000.0}))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"power_kWh\")\n  |> map(fn: (r) => ({r with power_kWh: r.P1 + r.P2 + r.P3 }))\n  |> timeShift(duration: -23h)     \n  |> aggregateWindow(every: 1d, fn: sum, column: \"power_kWh\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])"
    }
   ]
  },
  {
   "title": "More",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\" or r[\"_field\"] == \"P2\" or r[\"_field\"] == \"P3\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n//  |> aggregateWindow(every: 60s, fn: mean)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with Ptot: r.P1 + r.P2 + r.P3}))\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])  \n // |> yield(name: \"mean\")\n  ",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"U1\" or r[\"_field\"] == \"U2\" or r[\"_field\"] == \"U3\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n\n  ",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"I1\" or r[\"_field\"] == \"I2\" or r[\"_field\"] == \"I3\" or r[\"_field\"] == \"I4\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"]) \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\n\n  ",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Frequenz",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"F1\" or r[\"_field\"] == \"F2\" or r[\"_field\"] == \"F3\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Energy consumption",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Wm" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Ec1\" or r[\"_field\"] == \"Ec2\" or r[\"_field\"] == \"Ec3\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with Ec_tot: r.Ec1 + r.Ec2 + r.Ec3}))\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n     //|> yield(name: \"mean\")\n  ",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Energy production",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Wm" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "data",
       "query": "from(bucket: \"meteringdata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Ep1\" or r[\"_field\"] == \"Ep2\" or r[\"_field\"] == \"Ep3\")\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with Ep_tot: r.Ep1 + r.Ep2 + r.Ep3}))\n  |> drop(columns: [\"mac\",\"_start\", \"_stop\", \"type\"])\n\n  ",
       "select": [
        [
         { "params": [ "P1" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}